name: 2020-jgi-tech-talk
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - bcalm=2.2.1
    - snakemake-minimal=5.8.1
    - jq
    - blast
    - mummer
    - pymummer
    - cython=0.29.14
    - screed=1.0.1
    - sourmash=3.3.0
    - khmer=3.0.0a3
    - pandas=0.25.3
    - numpy=1.17.3
    - pytest=5.3.2
    - sortedcontainers=2.1.0
    - mypy=0.750
    - vim
    - pip
    - pip:
      - https://github.com/dib-lab/pybbhash/archive/spacegraphcats.zip
      - git+https://github.com/spacegraphcats/spacegraphcats.git
      - mmh3
      - matplotlib_venn
